### ISSUE TITLE
Design remote command format

### ISSUE THREAD

**Issue by claytondus** [claytondus/cdnwsh#19]

**Comment by nwilder0** [comment]
So, the simple way would be to just take the string entered at the remote shell on the client and pass it straight as the payload of a tcp send to the server who will extract the data payload and pass it straight to the same command parser that handles commands entered locally.  Results could then be returned in a similar manner.  Essentially there is no command format other than the original shell commands with their parameters.  And the client is just a basic terminal.

If you want to make more efficient use of bandwidth, then we could parse, do basic error checking and serialization on the client side and then pass the tcp data as a command specific struct that the server understands.  The client side code is a lot more complicated though in this situation.

**Comment by claytondus** [comment]
I think we could get away with the first option.  Telnet is the canonical example.  http://www.tcpipguide.com/free/t_TelnetProtocol.htm

**Comment by nwilder0** [comment]
Sounds good.
