### ISSUE TITLE
Task division

### ISSUE THREAD

**Issue by nwilder0** [claytondus/cdnwsh#20]
Do you want to divide tasks by just assigning issues to ourselves?  Or we can logically divide things up in this issue and then use that to assign.  Either way I'll wait till you weigh in the design issues before writing any code.

**Comment by claytondus** [comment]
I think taking issues would work best.  Just make sure whatever we're working on gets an issue defined so we don't overlap.

**Comment by nwilder0** [comment]
okay, will do
