### ISSUE TITLE
compile issues

### ISSUE THREAD

**Issue by nwilder0** [claytondus/cdnwsh#26]
I just pushed an update with some additional shell/server stuff, but be aware that some of the linux network header files don't work with gcc under c11 so I removed that item from the makefile.  However, that also apparently activates a header file that has the __USE_ATFILE definition, so have to remove that line from blockdev.c in order to get the project to compile (I left that update out of the push since I figured you might be making changes to blockdev.)

**Comment by nwilder0** [comment]
@claytondus

**Comment by claytondus** [comment]
Will they work with c99?  The only feature I really used was an inline declaration in a for loop, so I can live without it.

**Comment by claytondus** [comment]
Fixed it by changing to gnu11
