### ISSUE TITLE
Connect shell to fs commands

### ISSUE THREAD

**Issue by claytondus** [claytondus/cdnwsh#37]

**Comment by nwilder0** [comment]
So, it looks like any error output you're generating in the functions is going to stderr with the check() macro, right?  So, do you see any issues with me just redirecting stderr in the shell functions with getbuf() so the output is copied into a string that can be sent to a remote client?

Of course, the error will still be echo'd to stderr on the server, but that might be desirable anyway.

**Comment by claytondus** [comment]
The final builds can have the NDEBUG flag turned on which suppresses these.   The actual error is propagated by the return value.  If you want, you can do the redirection, but it isn't necessary.

**Comment by nwilder0** [comment]
Okay, I see that although it seems like the only code returned is -1, right?
And since check() resets errno are you thinking that users will just get a generic "command x failed" type message?
If so, that's fine, it's easy enough to do.

**Comment by claytondus** [comment]
Right, if I had more time I'd set errno.  Actually, the check() calls log to stderr even if NDEBUG is on, so this output can be redirected.  Again, not a priority.

**Comment by nwilder0** [comment]
tree is linked that's the last
