### ISSUE TITLE
cat_num is segfaulting when int is 0

### ISSUE THREAD

**Issue by claytondus** [claytondus/cdnwsh#40]

**Comment by claytondus** [comment]
cd dir1
ls
open file1.txt w

#0  0x00007ffff778be4c in __GI__IO_str_overflow (fp=0x7fffffffd970, c=48) at strops.c:146
#1  0x00007ffff778a70c in __GI__IO_default_xsputn (f=0x7fffffffd970, data=<optimized out>, n=1) at genops.c:480
#2  0x00007ffff77597df in _IO_vfprintf_internal (s=s@entry=0x7fffffffd970, format=<optimized out>, format@entry=0x407d2b "%d", ap=ap@entry=0x7fffffffda98) at vfprintf.c:1660
#3  0x00007ffff777f9db in __IO_vsprintf (string=0x0, format=0x407d2b "%d", args=args@entry=0x7fffffffda98) at iovsprintf.c:42
#4  0x00007ffff77635c7 in __sprintf (s=<optimized out>, format=<optimized out>) at sprintf.c:32
#5  0x00000000004025fb in cat_num (a=0x62e3d0 "SUCCESS, fd = ", n=0) at src/shell.c:72
#6  0x0000000000402e6d in sh_open (cmd_argc=2, cmd_argv=0x7fffffffdc40) at src/shell.c:231
#7  0x000000000040296a in run_cmd (cmdstr=0x7fffffffdd20 "open file1.txt w\n") at src/shell.c:126
#8  0x0000000000402147 in run () at src/server.c:202
#9  0x00000000004040fd in main (argc=1, argv=0x7fffffffdf58) at src/cdnwsh.c:24

**Comment by nwilder0** [comment]
sorry, fixed that a little while ago, just forgot to commit while I was looking at some other stuff
