### ISSUE TITLE
Decide on block size

### ISSUE THREAD

**Issue by claytondus** [claytondus/cdnwsh#6]

**Comment by nwilder0** [comment]
for this lab, I vote for the standard x86: 4KB

this will give us 25,600 blocks (and max files) for the required 100MB virtual disk file
and 4KB gives us plenty of space for other things

we could drop it to 1KB or 2KB though if you want, but if we permit the standard 255 character limit for file/directory names then the 1KB would permit less than 4 directory entries per block (assuming max filename).

or we could live dangerously and have 4KB be the default but allow mkfs to accept a block size parameter

**Comment by claytondus** [comment]
Agreed, 4KB is right.
