### ISSUE TITLE
Design inode structure

### ISSUE THREAD

**Issue by claytondus** [claytondus/cdnwsh#7]

**Comment by nwilder0** [comment]
So here are my thoughts...

For the block pointer, 2 bytes will give us 64K blocks which will fit for the 100MB file if we use 4KB block size but it is kind of small and at a 4KB block size even just a double indirect already goes well over the 64K blocks that 2 bytes can address.  So, I'm thinking we could just go with the ext2/older-x86 standard of 4 bytes and it will cover any virtual file system up to 16TB (w/ 4KB blocks).  

For the inode itself, I figure the following fields:  
- type: 1 byte (we really only need file or directory)
- size: 4 bytes (4GB file limit seems reasonable for this lab)
- parent: inode pointer - 4 bytes (I didn't see this in the unix spec but it seems like it will simplify our algorithms)
- created/modified/accessed: 12 bytes (4 bytes each to hold epoch timestamps)
- data block pointers: 40 bytes (10 \* 4) it seems easiest to use the following (loosely based on the linux standard of 15 pointers - 15 minus the triple indirect that is not needed and a few directs to even out the bytes):
  - 8 direct pointers
  - 1 single indirect
  - 1 double indirect

At a 4KB block the double indirect permits 4GB file size, so it seems like a triple isn't needed.  So, these fields should come to 61 bytes and we can pad it out to 64 bytes.  Using the upper limit of one file per block in the 100MB virtual file, the inodes (25,300) shouldn't take more than 1.5MB.  Of course, one inode per block is probably inefficient in most use cases.  And it seems like ext3/4 defaults to 1 inode per 16KB of block space.  So, we could do something like that, but then we'd need to error handle running out of inodes.

Do you see anything I missed or any other thoughts?

**Comment by claytondus** [comment]
I'm not sure what the parent inode pointer is for; what would it point to?  I think 1 inode : 4 blocks would be sufficient (6400 files).

**Comment by nwilder0** [comment]
I was thinking the parent pointer could be used as a shortcut to getting the containing directory, so that it wouldn't have to be held as a separate variable (also directories wouldn't need a pointer the parent folder's inode within the directory listing), but now that I think about it, it would probably be a little tricky to pull off, and we don't really need the optimization.

**Comment by nwilder0** [comment]
adding inode, inode pointer, block, etc structs and defines to fs.h
