### ISSUE TITLE
Design directory tree

### ISSUE THREAD

**Issue by claytondus** [claytondus/cdnwsh#8]

**Comment by nwilder0** [comment]
I looked at this site as a loose guide: http://www.nongnu.org/ext2-doc/ext2.html#DIRECTORY
So I guess there are two basic ways to go with this: disk space efficient with dynamic entry sizes adjusted to the size of the file name or fixed size entries.

Fixed size could be faster, but I suspect only if we align them with blocks - so probably a 256 byte entry size, which means trimming the names down to 250 or so.  With fixed size we wouldn't need the rec_len or name_len field (assuming names were null terminated or something like that).

Or we could just use the more efficient dynamic sized entry design very similar to that in the ext2 spec.

**Comment by claytondus** [comment]
I think the dynamic sizing is simple enough to implement.  I think most filenames will come in well under 250 chars.

**Comment by nwilder0** [comment]
okay, we'll give it a shot :-)

**Comment by claytondus** [comment]
Implementing directory tree:
opendir(): load directory into memory
readdir(): move through entries
closedir(): release directory memory

**Comment by claytondus** [comment]
Directory tree traversal is pretty solid now.  I can cd all over the place, absolute and relative.
