### ISSUE TITLE
Design superblock

### ISSUE THREAD

**Issue by claytondus** [claytondus/cdnwsh#9]

**Comment by nwilder0** [comment]
so, using the ext2 spec as a guide, i think the fields we need are as follows:  
- probably needed:
  - inode_count: 4 bytes
  - block_count: 4 bytes
  - block_size: 2 bytes
  - first_data_block: 4 bytes (unless we want to assume block 104)
- would make some things easier, but would need to be maintained:
  - free_inode_count: 4 bytes
  - free_block_count: 4 bytes
  - last_mount_time: 4 bytes
  - last_write_time: 4 bytes
- might be needed or at least make things look more like a functional file system:
  - version: 1 byte
  - state: 1 byte (to differentiate between a file system just loaded and after superblock, free bitmaps, inode table are checked)
  - free_blocks_block: 4 bytes (unless we assume it's block 2)
  - free_inodes_block: 4 bytes (unless we assume it's block 3)
  - inodes_block: 4 bytes (unless we assume is blocks 4-103)

Thoughts?

**Comment by claytondus** [comment]
I think we need a free inode and block count, last mount and write probably not. If we know how many blocks and inodes there are, and assuming block and inode bitmaps fit in 1 block each, it's easy to find them without storing their location.

**Comment by nwilder0** [comment]
okay, sounds good
